use 5.006;  # our
use strict;
use warnings;

package Policy;

our $VERSION = '0.001000';

# ABSTRACT: Kent Failed To Provide An Abstract

# AUTHORITY

use Moo;

no Moo;

1;

__END__

=pod

=encoding UTF-8

=head1 NAME

Policy - Kent Failed To Provide An Abstract

=head1 VERSION

version 0.000000

=head1 AUTHOR

Kent Fredric <kentnl@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2015 by Kent Fredric <kentfredric@gmail.com>.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
